@page "/docentes/create"
@using Microsoft.EntityFrameworkCore
@using Momentum.UI.Models
@inject IDbContextFactory<Momentum.UI.Data.AppDbContext2> DbFactory
@inject NavigationManager NavigationManager

<PageTitle>Create</PageTitle>

<h1>Create</h1>

<h2>Docentes</h2>
<hr />
@if (!String.IsNullOrEmpty(ErrorMessage))
{
    <div class="alert alert-danger">@ErrorMessage</div>
}

<div class="row">
    <div class="col-md-4">
        <EditForm method="post" Model="@Docentes" OnValidSubmit="AddDocentes" FormName="create" Enhance>
            <DataAnnotationsValidator />
            <ValidationSummary class="text-danger" role="alert" />
            <div class="mb-3">
                <label for="nome" class="form-label">Nome:</label>
                <InputText id="nome" @bind-Value="Docentes.Nome" class="form-control" aria-required="true" />
                <ValidationMessage For="() => Docentes.Nome" class="text-danger" />
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email:</label>
                <InputText id="email" @bind-Value="Docentes.Email" class="form-control" aria-required="true" />
                <ValidationMessage For="() => Docentes.Email" class="text-danger" />
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </EditForm>
    </div>
</div>

<div>
    <a href="/docentes">Back to List</a>
</div>

@code {
    public string ErrorMessage { get; set; } = string.Empty;

    [SupplyParameterFromForm]
    private Docentes Docentes { get; set; } = new();

    // To protect from overposting attacks, see https://learn.microsoft.com/aspnet/core/blazor/forms/#mitigate-overposting-attacks.
    private async Task AddDocentes()
    {
        using var context = DbFactory.CreateDbContext();
        try
        {
            context.Docentes.Add(Docentes);
            await context.SaveChangesAsync();
            NavigationManager.NavigateTo("/docentes");
        }
        catch (Exception ex) when (ex is not NavigationException)
        {
            if (ex.InnerException != null && ex.InnerException.Message.Contains("UNIQUE"))
            {
                ErrorMessage = "Este email já está registado.";
            }
            else
            {
                ErrorMessage = ex.Message;
            }
        }
        //catch (Exception ex)
        //{
        //    ErrorMessage = $"Erro inesperado: {ex.Message}";
        //}
    }
}
